version: "3"
services:
  app:
    container_name: pbl-app
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    container_name: pbl-db
    image: mysql:8.0.21
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: pbl-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
