version: "3"
services:
  flask_app:
    container_name: pbl-flask_app
    build: ./flask_app
    links:
      - db
    volumes:
      - ./flask_app:/app
      - socket:/tmp
    command: /bin/bash -c "uwsgi --ini /app/app.ini"
    #ports:
      #- "5000:5000"

  web:
    container_name: pbl-web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

  db:
    container_name: pbl-db
    image: mysql:8.0.21
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: pbl-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  socket:
